import Registration from './Registration';
import Home from './Home';
import CreateTeamForm from './CreateTeamForm';
import CreateProjectForm from './CreateProjectForm';
import { EditTaskForm } from './EditTaskForm';
import { CreateTaskForm } from './CreateTaskForm';
import { DeleteTaskForm } from './DeleteTaskForm';
import { DeleteProjectForm } from './DeleteProjectForm';
import { DeleteTeamForm } from './DeleteTeamForm';
export { Registration, CreateTeamForm, Home, CreateProjectForm, EditTaskForm, CreateTaskForm, DeleteTaskForm, DeleteProjectForm, DeleteTeamForm};